config/routes.rb
Rails.application.routes.draw do
  resources :orders
  root to: 'pages#welcome'
  resources :users
  resources :pages
  resources :products do 
    resources :comments
  end
  resources :categories
#  resources :carts
  get 'user', to: 'users#show'
  get 'edit', to: 'users#edit'
  post 'users/update'
  get 'carts/show'
  get 'carts', to: 'carts#index'
  get 'categories', to: "categories#index"
  post 'user/user_create_by_admin', to: "users#create_by_admins"
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get '/products/:id/comments/:id', to: 'comments#show', as: 'comment'
  get '/products/:id/comments/new', to: 'comments#new', as: 'comment_new'
  get '/products/:id/comments/', to: 'comments#index', as: 'comment_index'
  get 'toggle/:id', to: 'products#toggle', as: 'toggle'
  get 'clear', to: 'carts#clear'
  get 'close/:id', to: 'orders#close', as: 'close'
  get 'cancel/:id', to: 'orders#cancel', as: 'cancel'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
  belongs_to :user
  validates :body, presence: true
  validates :product_id, presence: true
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authorize_user, only: [:new, :create, :destroy]
  before_action :authorize_admin_or_owner, only: [:destroy]

  def index
    @product = Product.find(params[:product_id])
    @comments = @product.comments
  end 

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @comment = Product.find(params[:product_id]).comments.new
  end

  def create
    @product = Product.find(params[:product_id])
    @comment = @product.comments.new(comment_params)
    if @comment.save
      redirect_to product_path(@product)
    else
      render 'new'
    end
  end

  def destroy
    if @comment.destroy
      flash.keep[:notice] = "Successfully deleted comment!"
      redirect_to root_path
    else
      flash.keep[:error] = "Cannot Delete comment"
    end
  end

  protected

  def comment_params
    params.require(:comment).permit(:body, :user_id)
  end

  def authorize_admin_or_owner
    @comment = Comment.find(params[:id])
    redirect_to root_path unless is_admin? || current_user == @comment.user
  end


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/index.html.erb
<div class="container">
  <% @comments.each do |comment| %>
    <div class="card">
      <div class="card-header">Comment By <%= comment.user.username =%></div>
      <div class="card-body">
        <h5 class="card-title">Comment for <%= comment.product.name =%> product</h5>
        <p class="card-text"><%= comment.body =%></p>
      <%= button_to "delete", comment_path(comment), :method=>:delete, :class=>:destroy, class: "btn btn-danger" %>
      </div>
    </div>
  <% end %>
</div>

app/views/comments/new.html.erb
<%= form_for @comment, url: {controller: "comments", action: "create"}  do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= "#{pluralize(@comment.errors.count, "Error")} prohibited this comment from being saved:" %></h2>
      <ul>
        <% @comment.errors.full_messages.each do |msg| %>          
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.text_area :body, placeholder: "Enter Your Comment", class: "form-control" %><br>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.submit "Post Comment", class: "btn btn-primary" %>
<% end %>