config/routes.rb
Rails.application.routes.draw do
  resources :orders
  root to: 'pages#welcome'
  resources :users
  resources :pages
  resources :products do 
    resources :comments
  end
  resources :categories
#  resources :carts
  get 'user', to: 'users#show'
  get 'edit', to: 'users#edit'
  post 'users/update'
  get 'carts/show'
  get 'carts', to: 'carts#index'
  get 'categories', to: "categories#index"
  post 'user/user_create_by_admin', to: "users#create_by_admins"
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get '/products/:id/comments/:id', to: 'comments#show', as: 'comment'
  get '/products/:id/comments/new', to: 'comments#new', as: 'comment_new'
  get '/products/:id/comments/', to: 'comments#index', as: 'comment_index'
  get 'toggle/:id', to: 'products#toggle', as: 'toggle'
  get 'clear', to: 'carts#clear'
  get 'close/:id', to: 'orders#close', as: 'close'
  get 'cancel/:id', to: 'orders#cancel', as: 'cancel'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :cart
  has_one :user, through: :cart
  has_and_belongs_to_many :products

  validates :is_closed, :inclusion => { :in => [true, false] }

  def price
    price = 0
    for p in products
      price += p.price.to_f
    end
    price
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include SessionsHelper
  include UsersHelper
  before_action :authorize_user
  before_action :authorize_cart, except: [:index]
  before_action :authorize_owner, only: [:destroy]
  before_action :filled_cart, only: [:new, :create]

  def index
    @orders = is_admin? ? Order.all.select { |o| !o.is_closed } : current_user.orders
  end

  def new
    @order = Order.new
    @products = current_user.cart.products
  end

  def create
    @product_ids = []
    @cart = current_user.cart
    @cart.products.each { |p| @product_ids << p.id }
    @order = Order.new(order_params)
    @order.product_ids = @product_ids
    if @order.save
      @cart.orders.any? ? @cart.products = [] : @cart.destroy
      redirect_to order_path @order
    else
      render 'new'
    end
  end

  def close
    @order = Order.find(params[:id])
    @order.is_closed = true
  end

  def cancel
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to root_path
  end

  def show
    @order = Order.find(params[:id])
  end

  def destroy
    @order = Order.find(params[:id])
    if @order.destroy
      redirect_to user_path current_user
    else
      redirect_to order_path @order
    end
  end

  protected

  def order_params
    params.require(:order).permit(:user_id, :cart_id, product_ids:[])
  end

  def authorize_admin
    redirect_to root_path unless is_admin?
  end

  def authorize_user
    redirect_to root_path if current_user.nil?
  end

  def authorize_owner 
    redirect_to root_path unless @order.user == current_user
  end

  def authorize_owner_or_admin
    redirect_to root_path unless is_admin? && current_user == Order.find(params[:id]).user
  end

  def authorize_cart
    redirect_to root_path if current_user.cart.nil? && is_admin?
  end

  def filled_cart
    redirect_to root_path unless current_user.cart.products.any?
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
  def userable_status order
    return order.is_closed ? 'You Got and Paid That Already!' : 'Wait for it...'
  end
end

app/views/orders/index.html.erb
<% @orders.each do |o| %>
  <div class="card m-5" style="width: 28rem;">
    <div class="card-body">
      <h5 class="card-title"><%= o.price =%>$</h5>
      <h6 class="card-subtitle mb-2 text-muted"><%= o.products.count %></h6>
      <%= userable_status o %><br>
      <% if is_admin? %>
        for <%= o.user.username %> (id: <%= o.user.id %>)<br>
        <%= link_to 'Close Order', close_path(o) %>
      <% else %>
        <%= link_to "See Order", order_path(o) %><br>
        <%= link_to "Cancel Order", cancel_path(o) %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/orders/new.html.erb
<div class="container"><br>
  <h1>Create Order</h1><br>
  <%= form_for :order, url: {action: "create"} do |f| %>
    <% if @order.errors.any? %>
      <div id="error_explanation">
        <h2><%= "#{pluralize(@order.errors.count, "Error")} prohibited this order from being saved:" %></h2>
        <ul>
          <% @order.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.collection_check_boxes :product_ids, @products, :id, :name do |d| %>
      <div class="collection-check-box">
        <%= d.check_box %>
        <%= d.label %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.hidden_field :cart_id, value: current_user.cart.id %>
      </div>
    <% end %>
    <%= f.submit "Create Order", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/orders/show.html.erb
<div class="container">
  <h1>Products:</h1>
    <table class="table mt-5 table-bordered">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
        <th>Status</th>
        <th>Category</th>
       <th>See Product</th>
      </tr>
      <% @order.products.each do |p| %>
        <tr>
          <td><%= p.id %></td>
          <td><%= p.name %></td>
          <td><%= p.description %></td>
          <td><%= p.price %>$</td>
          <td><%= status_to_string p %></td>
          <td><%= p.category.title %></td>
          <td><%= link_to "See", product_path(p), :method=>:get, :class=>:show %></td>
        </tr>
      <% end %>
    </table>
    <h3>Price: <%= @order.price %>$</h3> (koonet paras haji)
</div>