config/routes.rb
Rails.application.routes.draw do
  resources :orders
  root to: 'pages#welcome'
  resources :users
  resources :pages
  resources :products do 
    resources :comments
  end
  resources :categories
#  resources :carts
  get 'user', to: 'users#show'
  get 'edit', to: 'users#edit'
  post 'users/update'
  get 'carts/show'
  get 'carts', to: 'carts#index'
  get 'categories', to: "categories#index"
  post 'user/user_create_by_admin', to: "users#create_by_admins"
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get '/products/:id/comments/:id', to: 'comments#show', as: 'comment'
  get '/products/:id/comments/new', to: 'comments#new', as: 'comment_new'
  get '/products/:id/comments/', to: 'comments#index', as: 'comment_index'
  get 'toggle/:id', to: 'products#toggle', as: 'toggle'
  get 'clear', to: 'carts#clear'
  get 'close/:id', to: 'orders#close', as: 'close'
  get 'cancel/:id', to: 'orders#cancel', as: 'cancel'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :orders
  has_and_belongs_to_many :products
  validates :user_id, uniqueness: true, presence: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include SessionsHelper
  include UsersHelper
  before_action :find_cart_no_admin, except: [:index]
  before_action :authorize_admin, only: [:index]

  def index
    @carts = Cart.all
  end

  def show
    @order = Order.new
  end

  def clear
    @cart.orders.any? ? @cart.products = [] : @cart.destroy
    redirect_to carts_show_path
  end

  protected

  def cart_params
    params.require(:cart).permit(:user_id)
  end

  def find_cart_no_admin
    @cart = current_user.cart
    redirect_to root_path if is_admin?
  end

  def authorize_admin
    redirect_to root_path unless is_admin?
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/index.html.erb
<div class="container">
  <table class="table mt-5 table-bordered">
    <tr>
      <th>ID</th>
      <th>User</th>
      <th>Products In</th>
    </tr>
    <% @carts.each do |p| %>
      <tr>
        <td><%= p.id %></td>
        <td><%= p.user.username %></td>
        <td><%= p.products.count %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/carts/show.html.erb
<% if @cart.products.any? %>
  <%= link_to "Empty Cart", clear_path, class: "btn btn-success" %>
  <% @cart.products.each do |product| %>
    <div class="card m-5" style="width: 28rem;">
      <image src="<%=(url_for(product.photo))%>" class="card-img-top">
      <div class="card-body">
        <h5 class="card-title"><%= product.name =%></h5>
        <h6 class="card-subtitle mb-2 text-muted"><%= product.category.title %></h6>
        <p class="card-text"><%= product.description =%></p>
      <%= link_to "Remove From Cart", toggle_path(product) %>
     </div>
    </div>
  <% end %>
<% else %>
  <h2>is empty bitch</h2>
<% end %>

  <h1>Set Order</h1><br>
  <%= form_for :order, url: {controller: "orders", action: "create"} do |f| %>
    <% if @order.errors.any? %>
      <div id="error_explanation">
        <h2><%= "#{pluralize(@order.errors.count, "Error")} prohibited this order from being saved:" %></h2>
        <ul>
          <% @order.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.hidden_field :cart_id, value: current_user.cart.id %>
      </div>
    <%= f.submit "Create Order", class: "btn btn-primary" %>
  <% end %>