config/routes.rb
Rails.application.routes.draw do
  resources :orders
  root to: 'pages#welcome'
  resources :users
  resources :pages
  resources :products do 
    resources :comments
  end
  resources :categories
#  resources :carts
  get 'user', to: 'users#show'
  get 'edit', to: 'users#edit'
  post 'users/update'
  get 'carts/show'
  get 'carts', to: 'carts#index'
  get 'categories', to: "categories#index"
  post 'user/user_create_by_admin', to: "users#create_by_admins"
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get '/products/:id/comments/:id', to: 'comments#show', as: 'comment'
  get '/products/:id/comments/new', to: 'comments#new', as: 'comment_new'
  get '/products/:id/comments/', to: 'comments#index', as: 'comment_index'
  get 'toggle/:id', to: 'products#toggle', as: 'toggle'
  get 'clear', to: 'carts#clear'
  get 'close/:id', to: 'orders#close', as: 'close'
  get 'cancel/:id', to: 'orders#cancel', as: 'cancel'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :photo
  has_many :comments, dependent: :destroy
  belongs_to :category
  has_and_belongs_to_many :carts
  has_and_belongs_to_many :orders
  validates :description, presence: true
  validates :name, presence: true, uniqueness: true
  validates :price, presence: true
  validates :photo, presence: true
  validates :status, :inclusion => { :in => [true, false] }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include SessionsHelper
  include UsersHelper
  before_action :authorize_admin, only: [:create, :new, :destroy]
  before_action :authorize_user, only: [:toggle]

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @comments = @product.comments
  end

  def new
    @categories = Category.all.select { |cat| cat.subcategories.length == 0 }
    @product = Product.new
  end

  def create
    @categories = Category.all.select { |cat| cat.subcategories.length == 0 }
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      render 'new'
    end
  end

  def edit
    @categories = Category.all.select { |cat| cat.subcategories.length == 0 }
    @product = Product.find(params[:id])
  end

  def update
    @categories = Category.all.select { |cat| cat.subcategories.length == 0 }
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to product_path @product
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product_id = @product.id
    if @product.destroy
      Cart.all.each do |cart|
        cart.destroy if cart.products.all? { |product| product.id == @product_id } && !cart.orders.any?
      end
      flash.keep[:notice] = "Successfully deleted product!"
      redirect_to products_path
    else
      flash.keep[:error] = "Cannot Delete product"
    end
  end

  def toggle
    Cart.create(user_id: current_user.id) if current_user.cart.nil?
    @cart = Cart.find_by(user_id: current_user.id)
    @products = @cart.products
    @product = Product.find(params[:id])
    if @products.include?(@product)
      @products.destroy @product
    elsif @product.status
      @products << @product
    end
    if !@cart.nil?
      @cart.destroy unless @cart.products.any?
    end
    redirect_to product_path @product
  end

  protected

  def product_params
    params.require(:product).permit(:name, :price, :description, :photo, :category_id, :status)
  end

  def authorize_admin
    redirect_to root_path unless is_admin?
  end

  def authorize_user
    redirect_to root_path if current_user.nil?
  end

end

app/helpers/products_helper.rb
module ProductsHelper
  def status_to_string product
    return product.status ? 'Availabe' : 'Unaivalbe'
  end
end

app/views/products/edit.html.erb
<%= form_for @product, url: {controller: "products", action: "update"}  do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= "#{pluralize(@product.errors.count, "Error")} prohibited this product from being saved:" %></h2>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>          
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  Current Image: <image src="<%=(url_for(@product.photo))%>" class="card-img-top" style="width: 200px;"><br>
  Change Image: <%= f.file_field :photo %><br>
  Current Category: <%= @product.category.title %><br>
  <%= f.select(:category_id, @categories.collect { |c| [ c.title, c.id ] }, { include_blank: true }) %><br>
  Current Name: <%= @product.name %><br>
  New Name: <%= f.text_field :name %><br>
  <%= f.text_area :description, placeholder: "New Description", class: "form-control" %><br>
  Current Price: <%= @product.price %><br>
  New Price: <input type="text" id="textInput" value="" name="OutputId">
  <%= f.range_field :price, in: 200..10000, step: 50, class: "custom-range", oninput: "OutputId.value = currency(this.value).format().replace('.00', '') + '$'" %><br>
  <%= f.label :status, "is avilable?" %> (current status: <%= status_to_string @product %>)
  <%= f.check_box :status %>
  <%= f.submit "Save Product", class: "btn btn-primary" %>
<% end %>
<script src="https://unpkg.com/currency.js@~1.2.0/dist/currency.min.js"></script>

app/views/products/index.html.erb
<div class="container">
  <table class="table mt-5 table-bordered">
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Status</th>
      <th>Comments Count</th>
      <th>Category</th>
      <th>Delete Product</th>
      <% if is_admin? %>
        <th>Edit Product</th>
      <% end %>
      <th>See Product</th>
    </tr>
    <% @products.each do |p| %>
      <tr>
        <td><%= p.id %></td>
        <td><%= p.name %></td>
        <td><%= p.description %></td>
        <td><%= p.price %>$</td>
        <td><%= status_to_string p %></td>
        <td><%= p.comments.length %></td>
        <td><%= p.category.title %></td>
        <td><%= button_to "delete", product_path(p), :method=>:delete, :class=>:destroy, class: "btn btn-danger" %></td>
        <% if is_admin? %>
          <td><%= link_to "Edit Product", edit_product_path(p) %></td>
        <% end %>
        <td><%= link_to "See", product_path(p), :method=>:get, :class=>:show %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/products/new.html.erb
<%= form_for @product, url: {controller: "products", action: "create"}  do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= "#{pluralize(@product.errors.count, "Error")} prohibited this product from being saved:" %></h2>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>          
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.file_field :photo %>
  <%= f.select(:category_id, @categories.collect { |c| [ c.title, c.id ] }, { include_blank: true }) %>
  <%= f.text_field :name %>
  <%= f.text_area :description, placeholder: "Enter Your Product", class: "form-control" %><br>
  <%= f.number_field :price, value: number_to_currency(f.object.price.to_f, delimiter: '', unit: '$'), step: 10 %>
  <%= f.label :status, "is avilable?" %>
  <%= f.check_box :status %>
  <%= f.submit "Post Product", class: "btn btn-primary" %>
<% end %>
<script src="https://unpkg.com/currency.js@~1.2.0/dist/currency.min.js"></script>

app/views/products/show.html.erb
<div class="container">
  <div class="card m-5" style="width: 28rem;">
    <image src="<%=(url_for(@product.photo))%>" class="card-img-top">
    <div class="card-body">
      <h5 class="card-title"><%= @product.name =%></h5>
      <h6 class="card-subtitle mb-2 text-muted"><%= @product.category.title %></h6>
      <p class="card-text"><%= @product.description =%></p>
    <% if is_admin? %>
      <%= button_to "delete", product_path(@product), :method=>:delete, :class=>:destroy, class: "btn btn-danger" %>
      Price: <%= @product.price %>$<br>
      Status: <%= status_to_string @product %><br>
      <%= link_to "Edit Product", edit_product_path(@product) %><br>
    <% end %>
    <% unless current_user.nil? %>
      <% if current_user.cart.nil? || current_user.cart.products.include?(@product) == false %>
        <%= link_to "Add To Cart", toggle_path(@product) %>
      <% else %>
        <%= link_to "Remove From Cart", toggle_path(@product) %>
      <% end %>
    <% end %>
    </div>
  </div>
  
  <h1>Commments For this Product</h2>
  <% if @comments.any? %>
    <% @comments.each do |comment| %>
      <div class="card">
        <div class="card-header">Comment By <%= comment.user.username =%></div>
        <div class="card-body"><%= comment.body %></div>
      </div>
    <% end %>
    <br>
  <% else %>
    <h4>There is no comment for this product yet :(</h4>
  <% end %>
  <%= link_to("Add Comment", comment_new_path(@product)) %><br>
   <%= link_to("See Comments", comment_index_path(@product)) %>
</div>